define({
    "BASELINE_DESCRIPTION":         "Description",
    "BASELINE_NAME":                "Nom",
    "CANCEL":                       "Annuler",
    "CLOSE":                        "Fermer",
    "CREATE_BASELINE":              "Cr\u00e9er la baseline",
    "CREATION_ERROR":               "Erreur lors de la cr\u00e9ation de la baseline",
    "DUPLICATE":                    "Dupliquer",
    "DUPLICATE_BASELINE":           "Dupliquer la baseline",
    "EDIT_BASELINE":                "Editer la baseline",
    "EXCLUDE":                      "Exclure l'article de la baseline",
    "ITERATION":                    "It\u00e9ration",
    "LATEST":                       "Toutes dernières versions des articles",
    "NEW_BASELINE":                 "Nouvelle baseline",
    "NUMBER":                       "Num\u00e9ro de l'article",
    "RELEASED":                     "Uniquement les articles finalis\u00e9s",
    "SAVE":                         "Enregistrer",
    "TYPE":                         "Type",
    "VERSION":                      "Version"
});