/*global define*/
define({
    ALL: 'All',
    DESCRIPTION: 'Description',
    BASELINE_OF: 'Baseline of',
    DUPLICATE: 'Duplicate',
    DUPLICATE_BASELINE: 'Duplicate baseline',
    EDIT_BASELINE: 'Edit baseline',
    EXCLUDE: 'Exclude part from baseline',
    NEW_BASELINE: 'New baseline',
    ADD_ISSUE: "Add a issue",
    ADD_REQUEST: "Add a request",
    AFFECTED_ELEMENT: "Affected items",
    CHANGE_ITEM_ASSIGNEE: "User Assigned",
    CHANGE_ITEM_CATEGORY: "Category",
    CHANGE_ITEM_PRIORITY: "Priority",
    DUE_DATE: "Due date",
    EDIT_ISSUE: "Edit the issue",
    EDIT_MILESTONE: "Edit the milestone",
    EDIT_ORDER: "Edit the order",
    EDIT_REQUEST: "Edit the request",
    INITIATOR: "Initiator",
    ISSUES: "Issues",
    MILESTONE: "Milestone",
    MILESTONES: "Milestones",
    NEW_ISSUE: "New change-issue",
    NEW_MILESTONE: "New milestone",
    NEW_ORDER: "New change-orders",
    NEW_REQUEST: "New change-request",
    ORDERS: "Orders",
    ORDERS_NUMBER: "Number of orders",
    REQUESTS: "Requests",
    REQUESTS_NUMBER: "Number of request",
    SEND: "Send",
    VIDEO_INVITE_ACCEPT: "Accept",
    VIDEO_INVITE_REJECT: "Reject",
    COLLABORATIVE_INVITE: "You are invited to join a collaborative room",
    COLLABORATIVE_WITHDRAW_INVITATION: "Invitation canceled",
    ONLINE: "En ligne",
    OFFLINE: "Hors ligne",
    NO_DATA: "No data available in table",
    NO_FILTERED_DATA: "No matching records found",
    DATE_SORT: "date_sort_en",
    ACTIVITY_STATE_PLACEHOLDER: "New state",
    ADD_ACTIVITY: "Add activity",
    ADD_DOCUMENT: "Add document",
    ADD_NEW_TAG: "Enter a new tag",
    ADD_TASK: "Add task",
    ADVANCED: "Advanced",
    ALL_TASKS: "All",
    APPROVE_TASK: "Mark task as done",
    ATTACHED_FILES: "Files",
    BOOLEAN: "Boolean",
    CHECKOUTS: "Checked out",
    CLEAR: "Clear",
    CLOSURE_COMMENT: "Closure comment",
    COMMENT: "Comment",
    CONTENT: "Content",
    CONTENT_HELP: "Document content",
    COPY: "Copy",
    COPY_WORKFLOW: "Copy the workflow",
    CURRENT_TAGS: "Tags related",
    CURRENT_WORKFLOW: "Current workflow",
    DATE: "Date",
    DELETE_ACTIVITY: "Remove activity",
    DELETE_FOLDER_QUESTION: "Delete the folder?",
    DELETE_LINKED_ITEM: "Delete link",
    DELETE_TAG_QUESTION: "Delete the tag?",
    DELETE_TASK: "Remove task",
    DOCUMENT: "Document",
    DOCUMENT_S_DESCRIPTION: "Document description",
    DOCUMENT_S_REFERENCE: "Document ID",
    DOCUMENT_S_TITLE: "Document title",
    DROP_FILE_HERE: "or drop file here",
    EDIT: "Edit",
    EDIT_LINKED_DOCUMENTS: "Edit links",
    EXISTING_TAGS: "Tags available",
    FILTER: "Filter",
    FINAL_STATE_PLACEHOLDER: "Final state",
    FOLD_TASK: "Minimize task",
    FOLDER: "Folder",
    FOLDERS: "Folders",
    FOLDER_S_NAME: "Folder name",
    GOTO_SERIAL_MODE: "Switch activity to serial",
    GOTO_PARALLEL_MODE: "Switch activity to parallel",
    HISTORY: "History",
    INSTRUCTIONS: "Instructions",
    ITERATION_CHANGE: "Iteration change",
    LAST_ITERATION: "Current iteration",
    MASK_HELP: "Define the mask format for the IDs of documents/parts that will instanciate this template.</br></br>Additionally to any regular characters, you can use '#' symbol for any valid number and '*' for any character.</br></br>For instance 'FAX-***-##' will accept 'FAX-AZE-12' as a valid ID.",
    NB_TASKS_TO_COMPLETE: "Tasks to complete",
    NEW_DOCUMENT: "New document",
    NEW_FOLDER: "New folder",
    NEW_TAG: "New tag",
    NEW_TEMPLATE: "New document template",
    NEW_WORKFLOW: "New workflow",
    NOTIFICATIONS: "Notifications",
    PARALLEL_ACTIVITY: "In parallel, require ",
    PATH: "Folder",
    REFERENCE_HELP: "Document ID",
    REJECT_TASK: "Reject task",
    RELAUCNH_ACTIVITY_SELECTOR: "Relaunch activity if rejected",
    RENAME_WORKFLOW_COPY: "Name of the copy",
    ROLE: "Role",
    NUMBER: "Number",
    OK: "OK",
    REFERENCES: "Objects",
    RENAME: "Rename",
    REVISION_NOTE_PROMPT_LABEL: "The revision note has not been defined. Do you want to add it?",
    REVISION_NOTE_PROMPT_CANCEL: "Ignore",
    REVISION_NOTE_PROMPT_OK: "Add the revision note",
    SAVED: "Saved",
    SELECT_FILE: "Choose a file",
    SERIAL_ACTIVITY: "In serial",
    SIGN_TASK: "Signing up",
    START: "Start",
    STATE_CHANGE: "State change",
    SUBSCRIBE_ITERATION_CHANGE: "Subscribe to iteration change notifications",
    SUBSCRIBE_STATE_CHANGE: "Subscribe to document state change notifications",
    TAGS: "Tags",
    TAGS_HELP: "Tags list, comma separated",
    TAGS_TO_ADD: "Tags to add",
    TASK_APPROVED_ON: "Task done on",
    TASK_CLOSED_ON: "Task closed on",
    TASK_NAME_PLACEHOLDER: "New task",
    TASK_REJECT_ON: "Task reject on",
    TASKS: "Tasks",
    TASKS_IN_PROGRESS: "In progress",
    TEMPLATE: "Template",
    TEMPLATES: "Templates",
    TEXT: "Text",
    TITLE_HELP: "Document title",
    UNFOLD_TASK: "Edit task",
    UNSUBSCRIBE_ITERATION_CHANGE: "Unsubscribe from iteration change notifications",
    UNSUBSCRIBE_STATE_CHANGE: "Unsubscribe from document state change notifications",
    URL: "URL",
    VALIDATION_FAILED_FOR: "Validation failed for ",
    VALUE: "Value",
    WORKFLOW_HISTORY: "History",
    WORKFLOW_LEGEND_COMPLETE: "Complete",
    WORKFLOW_LEGEND_INCOMPLETE: "Incomplete",
    WORKFLOW_LEGEND_INPROGRESS: "In progress",
    WORKFLOW_LEGEND_REJECTED: "Rejected",
    WORKFLOW_NAME_PLACEHOLDER: "New workflow name",
    WORKFLOWS: "Workflows",
    WORKSPACES: "Workspaces",
    MY_WORKSPACES: "My workspaces",
    ADMINISTRATED: 'Administrated',
    OTHERS: 'Others',
    DOCUMENTS_MANAGEMENT: 'Documents management',
    PRODUCTS_MANAGEMENT: 'Products management',
    CHANGES_MANAGEMENT: 'Changes management',
    DOCUMENTS: 'Documents',
    CHANGES: 'Changes management',
    COWORKERS: 'Coworkers',
    MY_ACCOUNT: 'My account',
    MY_ORGANIZATION: 'My organization',
    WORKSPACES_ADMINISTRATION: 'Workspaces administration',
    DOWNLOAD_DPLM_CLIENT: 'Download DPLM client',
    ABOUT_DOCDOKUPLM: 'About DocdokuPLM',
    LOGOUT: 'Logout',
    CREATE_PRODUCT: "Create Product",
    CREATE_PART: "Create part",
    DELETE_PRODUCT: "Delete Product",
    ROOT_PART_NUMBER: "Root part number",
    CANCEL_PART_CREATION: "Cancel part creation",
    MANAGE_PRODUCT: "Products management",
    ALL_PRODUCTS: "All products",
    EDIT_PRODUCT: "Edit product",
    DELETE_PRODUCT_CONFIRM: "Are you sure to want to delete this product ?",
    DELETE_PRODUCT_ERROR: "Error on product deletion",
    VISUALIZE_PRODUCT: "Visualize product",
    LOCK_ATTRIBUTES: "Freeze attributes structure",
    MANDATORY: "Mandatory",
    _DATE_SHORT_FORMAT: "yyyy-mm-dd",
    _DATE_PICKER_DATE_FORMAT: "yyyy-mm-dd",
    _VALIDATION_PATTERN_DATE: "\\d{4}-\\d{2}-\\d{2}",
    _VALIDATION_PATTERN_NUMBER: "^\\-?\\d+(\\.\\d+)?$",
    _VALIDATION_PATTERN_TIME: "\\d{2}:\\d{2}",
    BASELINE: "Baseline",
    CHOOSE_A_PRODUCT: "Choose a product",
    CREATION_ERROR: "An error occurred during creation",
    EDIT_PRODUCT_INSTANCE: "Edit the deliverable",
    NEW_PRODUCT_INSTANCE: "New deliverable",
    PRODUCT_INSTANCES: "Deliverable",
    SERIAL_NUMBER: "Serial number",
    UPDATE_AUTHOR: "Update author",
    UPDATE_DATE: "Update date",
    ADD_PART: "Add a part",
    ADVANCED_SEARCH: "Advanced search",
    AUTHOR_DOCUMENT_HELP: "Author of the document",
    AUTHOR_PART_HELP: "Author of the part",
    BASELINES: "Baselines",
    CREATE: "Create",
    CREATE_BASELINE: "Create a baseline",
    CREATE_BASELINE_LATEST: "Create baseline with last released part",
    CREATE_BASELINE_RELEASED: "Create baseline with last part",
    CREATE_NEW_VERSION: "Create new version",
    DELETE: "Delete",
    DELETE_SELECTION: "Delete selection",
    DELETE_SELECTION_QUESTION: "Delete selection?",
    FILES: "Files",
    FIRST_PAGE: "First page",
    GO_TO_PAGE: "Go to page ...",
    ID_GENERATION: "Id generation",
    ITERATION_NOTE: "Iteration note",
    ITERATION_NOTE_PROMPT_CANCEL: "Ignore",
    ITERATION_NOTE_PROMPT_LABEL: "The iteration note has not been defined. Do you want to add it?",
    ITERATION_NOTE_PROMPT_OK: "Add iteration note",
    LAST_PAGE: "Last page",
    MASK: "Mask",
    NEW_PART: "New part",
    NEW_PART_TEMPLATE: "New part template",
    NEW_PRODUCT: "New product",
    NEW_VERSION: "New version",
    NEW_VERSION_OF: "New version of",
    NEXT_PAGE: "Next page",
    OBJECTS: "Objects",
    PART_NUMBER_HELP: "Number of the part",
    PART_TEMPLATE: "Part template",
    PART_TEMPLATES: "Templates",
    PARTS: "Parts",
    PREVIOUS_PAGE: "Previous page",
    PRODUCT_ID: "Product Id",
    PRODUCT_STRUCTURE: "Product structure",
    PRODUCTS: "Products",
    PUBLISH: "Publish",
    QUICK_SEARCH: "Quick search",
    RELEASE_SELECTION_QUESTION: "Release selection?",
    ROOT_PART: "Root part",
    SEARCH: "Search",
    STANDARD_PART_ALL: "All",
    STANDARD_PART_FALSE: "No",
    STANDARD_PART_TRUE: "Yes",
    TITLE: "Title",
    TYPE: "Type",
    DOCUMENT_TYPE_HELP: "Type of the document",
    PART_TYPE_HELP: "Type of the part",
    UNDO_CHECKOUT: "Cancel checkout",
    UNDO_CHECKOUT_QUESTION: "Undo checkout?",
    VERSION_HELP: "Version of the part",
    WORKFLOW: "Workflow",
    WORKSPACE: "Workspace",
    LAYERS: "Layers",
    NEW_LAYER: "New layer",
    NO_LAYERS: "No layers",
    PART_NUMBER: "Part Number",
    PART_NAME: "Part Name",
    VERSION: "Version",
    ITERATION: "Iteration",
    IS_STANDARD_PART: "Standard Part",
    AUTHOR: "Author",
    AMOUNT: "Amount",
    CHECKOUT_BY: "Checked out by",
    CREATION_DATE: "Creation date",
    CHECKOUT_DATE: "Checkout date",
    _DATE_FORMAT: "mm-dd-yyyy HH:MM:ss",
    CANCEL_CHECKOUT: "Undo check out",
    CHECKIN: "Check in",
    CHECKOUT: "Check out",
    DELETE_MARKER: "Delete marker",
    NEW_MARKER: "New marker",
    NAME: "Name",
    EMBED_SCENE: "Embed Scene",
    CONTROLS_SHORTCUTS: "Mouse/keyboard shortcuts",
    KEYBOARD_SHORTCUTS: "Keyboard shortcuts",
    MOUSE_CONTROLS: "Mouse controls",
    MOVE_FORWARD: "Move forward",
    MOVE_BACKWARD: "Move backward",
    MOVE_LEFT: "Move left",
    MOVE_RIGHT: "Move right",
    MOVE_UP: "Move up",
    MOVE_DOWN: "Move down",
    LEAVE_NAV: "Stop the navigation",
    MOVE: "move",
    MOVE_SCENE: "Move into the scene",
    LEFT_CLICK: "left click",
    RIGHT_CLICK: "right click",
    DBL_CLICK: "double click",
    ENTER_NAV: "Start the navigation",
    MARKER_INFO: "Get marker informations",
    SPACE: "space",
    ROTATE_SCENE: "Rotate the scene",
    SCROLL_UP: "scroll up",
    SCROLL_DOWN: "scroll down",
    GENERAL: "General",
    ATTRIBUTES: "Attributes",
    CAD_FILE: "CAD File",
    APPEND: "Add",
    STANDARD_PART: "Standard part",
    SUB_PARTS: "Assembly",
    CREATE_NEW_PART: "Create a new part",
    OR_ADD_PART: "Or add an existing part",
    NO_WEBGL: "No WebGL available or activated",
    TRUE: "True",
    FALSE: "False",
    LINKS: "Links",
    EXPORT: "Export",
    FULL_SCREEN: "Full screen",
    CONFIG_SPEC: "Config spec",
    LATEST: "Latest",
    SEARCH_PARTS: "Search parts",
    SEARCH_OPTIONS: "Search options",
    PART_NAME_HELP: "partName",
    SEARCH_PART_CALLED: "Search part called",
    SEARCH_PART_BEGINNING: "Search part beginning by",
    SEARCH_PART_ENDING: "Search part ending by ",
    FLYING_MODE: "Fly mode",
    TRACKBALL_MODE: "Trackball mode",
    ORBIT_MODE: "Orbit mode",
    FIT_VIEW: "Fit view",
    MARKERS_SIZE_MIN: "Reduce markers size",
    MARKERS_OPACITY: "Change markers opacity",
    MARKERS_SIZE_MAX: "Increase markers size",
    VIEW_MODE: "View mode",
    MARKERS: "Markers",
    COMPONENT_SELECTED: "Selected part",
    INSTANCE_SELECTED: "Selected instance",
    FLY_TO: "Fly to",
    LOOK_AT: "Look at",
    CLIPPING: "Clipping",
    TOGGLE_ALL_LAYERS: "Toggle all layers",
    APPEND_LAYER: "Create a new layer",
    SCENE_VIEW: "Scene view",
    BOM_VIEW: "Bom View",
    OPTIONS: "Options",
    TAKE_SCREENSHOT: "Take screenshot",
    GRID_SWITCH: "Show/Hide the grid",
    LIFECYCLE_STATE: "Life cycle state",
    REFERENCE: "ID",
    REVISION_NOTE: "Revision note",
    MODIFICATION_DATE: "Modification date",
    EXPLODE: "Explode",
    CUTPLAN: "Cut plan",
    ABSOLUTE: "Absolute",
    IN_PROGRESS: "Work in progress",
    RELATIVE: "Relative",
    RELEASE: "Release",
    RELEASED: "Released",
    MEASURE: "Measure",
    NAVIGATION: "Navigation",
    TRANSFORM_CONTROLS: "Transformation",
    ROTATE: "Rotate",
    SCALE: "Scale",
    REPLACE: "Reset",
    RESET_CAMERA: "Reset camera",
    SHOW_EDITED_MESHES: "Highlight edited meshes",
    COLLABORATIVE_LEAD: "Presenter",
    PENDING: "Absent participant",
    PARTICIPANT: "Participant",
    CREATE_ROOM: "Start a digital mockup review",
    INVITE: "Invite coworkers",
    EXIT: "Leave digital mockup review",
    WITHDRAW_INVITATION: "Withdraw invitation",
    GIVE_HAND: "Give the hand",
    COLLABORATIVE_NO_MASTER: "absent",
    COLLABORATIVE: "Co-browsing",
    NO_PARTICIPANT: "No participant. Invite users from Coworkers menu.",
    USERS_CONNECTED: "users connected",
    ROLES: "Roles",
    NEW_ROLE: "New role",
    MANAGE_ROLES: "Manage roles",
    ROLE_NAME: "Role name",
    ADD: "Add",
    ALERT_ROLE_IN_USE: "This role cannot be removed, because it's in use in a workflow",
    SHORTCUTS_TITLE: "Keyboard / mouse shortcuts",
    BLOCKER_TITLE: "Click to launch the scene",
    BLOCKER_TEXT: "(Z, Q, S, D = Move, SPACE = Up, CTRL = Down, MOUSE = Look around, ESC = Quit)",
    ACL: "ACL",
    USERS: "Users",
    GROUPS: "Groups",
    FORBIDDEN: "Forbidden",
    READ_ONLY: "Read only",
    FULL_ACCESS: "Full access",
    USE_ACL: "Use ACL ?",
    SHARE: "Share",
    CLOSE: "Close",
    SHARED_DOCUMENTS_TITLE: "Share document",
    SHARED_PARTS_TITLE: "Share part",
    PUBLIC_ACCESS_TITLE: "Public access to permalink",
    PRIVATE_SHARE_TITLE: "Private share",
    GENERATED_URL: "Generated url",
    PASSWORD: "Password",
    CONFIRM: "Confirm password",
    PASSWORD_NOT_CONFIRMED: "Password and Confirm password must match",
    EXPIRE_DATE: "Expiration date",
    FORM_HELPER: "Let these inputs empty if you don't want to specify a password or an expiration date",
    PUBLIC_SHARE: "Public share",
    PERMALINK: "Permalink",
    ACCEPT_VIDEO_INVITE: "Accept",
    REJECT_VIDEO_INVITE: "Reject",
    VIDEO_INVITE_NOTIFICATION_TITLE: "Video invite",
    VIDEO_INVITE_TEXT: "is inviting you to a video chat session",
    UNREACHABLE: "Cannot invite user, user is unreachable",
    ERROR: "Error",
    REMOTE_HANGUP: "Remote user hang up",
    CLOSING_PEER_CON: "Closing peer connection ...",
    CALL_TO_TITLE: "Call to",
    WAITING_USER_MEDIA: "Waiting user media ... Please accept the prompt from your browser.",
    REMOTE_TIMEOUT: "Remote user didn't answer in time. Call aborted ...",
    REMOTE_BUSY: "Remote user is busy. Call aborted ...",
    REMOTE_ACCEPT: "Remote user has accepted the call. Waiting for connection ...",
    REMOTE_REJECT: "Remote user has rejected the call. Call ended ...",
    REMOTE_OFFLINE: "Remote user is offline. Call ended ...",
    USER_MEDIA_FAILED: "Cannot access to your video input. Is this a WebRTC capable browser ?",
    VIDEO_INVITATION_SENT: "Invitation has been sent to remote user, waiting for him/her to accept",
    CONNECTING: "Connecting...",
    CANNOT_CREATE_PC: "Cannot create RTCPeerConnection object, WebRTC is not supported by this browse.",
    SESSION_CONNECTING: "Session connecting",
    SESSION_OPENED: "Session opened",
    REMOTE_STEAM_ADDED: "Remote stream added",
    REMOTE_STEAM_REMOVED: "Remote stream removed",
    WAITING_REMOTE_VIDEO: "Waiting for remote video.",
    CONNECTED: "Connected",
    DEVICE_ERROR: "Cannot access you audio/video device, please insure your browser is WebRTC capable, and if there's no exception for this website.",
    CHANNEL_NOT_READY_ERROR: "Cannot communicate with the call server. Please insure that your browser is websocket capable, or your internet provider doesn't block them.",
    LATEST_SHORT:"Latest versions",
    RELEASED_SHORT:"Latest released versions",
    OPEN_NEW_WINDOW:"Open in a new window",
    UPDATE_ACL_ERROR:"An error occurred while updating acl",
    CANNOT_DELETE_FILE:"Cannot delete file : ",
    BASELINE_DELETION_ERROR:"Cannot delete baseline : ",
    YOU_HAVE_BEEN_KICKED:"You have been kicked from the room",
    NOT_INVITED_COLLABORATIVE_ROOM:"You are not invited to join this room."

});