define({
    root: {
        "BASELINES":                    "Baselines",
        "BASELINE_DESCRIPTION":         "Description",
        "BASELINE_NAME":                "Name",
        "BASELINE_OF":                  "Baseline of",
        "CANCEL":                       "Cancel",
        "CHOOSE_A_PRODUCT":             "Choose a product",
        "CLOSE":                        "Close",
        "CREATE_BASELINE":              "Create baseline",
        "CREATE_BASELINE_LATEST":       "Create baseline with last released part",
        "CREATE_BASELINE_RELEASED":     "Create baseline with last part",
        "CREATION_ERROR":               "Error on baseline creation",
        "DELETE":						"Delete",
        "DELETE_SELECTION_?":			"Delete the selected element?",
        "DUPLICATE":                    "Duplicate",
        "DUPLICATE_BASELINE":           "Duplicate baseline",
        "EDIT_BASELINE":                "Edit baseline",
        "EXCLUDE":                      "Exclude part from baseline",
        "ITERATION":                    "Part iteration",
        "LATEST":                       "Very latest versions of parts",
        "NEW_BASELINE":                 "New baseline",
        "NUMBER":                       "Part number",
        "RELEASED":                     "Only released parts",
        "SAVE":                         "Save",
        "TYPE":                         "Type",
        "VERSION":                      "Part version"
    },
    "fr": true
});