/*global define*/
define({
	ABOUT_DOCDOKUPLM: 'A propos de DocdokuPLM',
	ABSOLUTE: 'Absolu',
	ACCEPT_VIDEO_INVITE: 'Accepter',
    ACCESS_RIGHTS: 'Droits d\'accès',
	ACL: 'ACL',
	ACTIVITY_STATE_PLACEHOLDER: 'Nouvel état',
	ADD_ACTIVITY: 'Ajouter une activité',
	ADD: 'Ajouter',
    ADD_CALCULATION: 'Ajouter un calcul',
    ADD_COMMENT: 'Ajouter un commentaire',
    ADD_DOCUMENT: 'Ajouter un document',
	ADD_ISSUE: 'Ajouter une anomalie',
	ADD_NEW_TAG: 'Saisir un nouveau libellé',
	ADD_PART: 'Ajouter un article',
	ADD_REQUEST: 'Ajouter une requête',
    ADD_REVISION_NOTE: 'Ajouter une note de révision',
	ADD_TASK: 'Ajouter une tâche',
    ADD_TEMPLATE_ATTRIBUTES:'Ajouter les attributs d\'exemplaire',
    ADMINISTRATED: 'Administrés',
	ADVANCED: 'Avancé',
	ADVANCED_SEARCH: 'Recherche avancée',
	AFFECTED_ELEMENT: 'Eléments affectés',
	ALERT_ROLE_IN_USE: 'Ce rôle ne peut être supprimé car il est utilisé dans un processus',
	ALL: 'Tous',
	ALL_PRODUCTS: 'Tous les produits',
	ALL_TASKS: 'Toutes',
	AMOUNT: 'Quantité',
	APPEND: 'Ajouter',
	APPEND_LAYER: 'Créer un nouveau calque',
	APPROVE_TASK: 'Marquer la tâche comme effectuée',
    ASSIGNED_ROLE_PRE_FILL:'Assignations par défaut',
    ASSIGNED_ROLE_REQUIRED:'Vous devez assigner au moins un utilisateur ou un groupe',
    ASSIGNED_USERS:'Utilisateurs assignés',
    ASSIGNED_USERS_PRE_FILL:'Utilisateurs assignés par défaut',
    ASSIGNED_USERGROUPS:'Groupes assignés',
    ASSIGNED_USERGROUPS_PRE_FILL:'Groupes assignés par défaut',
	ATTACHED_FILES: 'Fichiers joints',
    ASSIGNMENTS:'Assignations',
    ATTRIBUTES: 'Attributs',
	AUTHOR: 'Auteur',
	AUTHOR_LOGIN: 'Identifiant de l\'auteur',
	AUTHOR_NAME: 'Nom de l\'Auteur',
	AUTHOR_DOCUMENT_HELP: 'Auteur du document ou utilisateur ayant travaillé sur le document',
	AUTHOR_PART_HELP: 'Auteur de l\'article ou utilisateur ayant travaillé sur l\'article',
    AUTO_CHECKIN:'Libération automatique des articles réservés pour l\'import',
    AUTO_CHECKOUT:'Réservation automatique des articles non réservés',
	AVG: 'Moyenne',
    BACK:'Retour',
    BASED_ON: 'Baseline de référence',
	BASELINE: 'Baseline',
	BASELINE_DELETION_ERROR:'Impossible de supprimer la baseline : ',
	BASELINE_OF: 'Baseline de',
	BASELINES: 'Baselines',
    BEST_FIT_VIEW:'Meilleure vue',
	BLOCKER_TEXT: '(Z, Q, S, D = Déplacer, ESPACE = Haut, CTRL = Bas, SOURIS = Regarder autour, ECHAP = Quitter)',
	BLOCKER_TITLE: 'Cliquez pour lancer la visualisation',
	BOM_VIEW: 'Visualiser structure produit',
	BOOLEAN: 'Booléen',
    BY: 'par',
	CAD_FILE: 'Fichier CAO',
	CAD_FILES: 'Fichiers CAO',
	CALCULATIONS: 'Calculs',
	CALL_TO_TITLE: 'Appel en cours',
	CANCEL: 'Annuler',
	CANCEL_CHECKOUT: 'Annuler la réservation',
	CANCEL_PART_CREATION: 'Annuler la création de l\'article',
	CANNOT_CREATE_PC: 'Impossible de créer la connexion, votre navigateur ne supporte pas le WebRTC.',
	CANNOT_DELETE_FILE:'Impossible de supprimer le fichier : ',
	CHANGE_ITEM_ASSIGNEE: 'Utilisateur assigné',
	CHANGE_ITEM_CATEGORY: 'Catégorie',
	CHANGE_ITEM_PRIORITY: 'Priorité',
	CHANGES: 'Gestion des changements',
	CHANGES_MANAGEMENT: 'Gestion des changements',
	CHANNEL_NOT_READY_ERROR: 'Impossible de se connecter au serveur d\'appel, vérifiez que votre navigateur supporte les websocket, ou que votre FAI ne les bloque pas',
    CHECK_ALL: 'Tout sélectionner',
    CHECKED_IN: 'libéré',
	CHECKIN: 'Libérer',
    CHECKIN_DATE: 'Date de libération',
	CHECKOUT_BY: 'Réservé par',
	CHECKOUT_DATE: 'Date de réservation',
	CHECKOUT: 'Réserver',
	CHECKOUTS: 'Réservés',
    CHOICES:'Choix',
	CHOOSE_A_PRODUCT: 'Sélectionnez un produit',
    CHOSEN_OPTIONALS:'Articles optionnels exclus',
    CHOSEN_SUBSTITUTES:'Variantes choisies',
	CLEAR: 'Effacer',
	CLIPPING: 'Couper',
	CLOSE: 'Fermer',
	CLOSING_PEER_CON: 'Fermeture de la connexion ...',
	CLOSURE_COMMENT: 'Commentaire',
	COLLABORATIVE: 'Co-browsing',
	COLLABORATIVE_INVITE: 'Vous êtes invité à rejoindre une salle',
	COLLABORATIVE_KICKED: 'Vous n\'êtes plus dans la salle',
	COLLABORATIVE_LEAD: 'Présentateur',
	COLLABORATIVE_NO_MASTER: 'absent',
	COLLABORATIVE_NOT_INVITED:'Vous n\'avez pas été invité à cette salle.',
	COLLABORATIVE_WITHDRAW_INVITATION: 'Invitation annulée',
	COMMENT: 'Commentaire',
	COMPONENT_SELECTED: 'Article sélectionné',
	CONFIG_SPEC: 'Config spec',
	CONFIGURATION: 'Configuration',
	CONFIGURATIONS: 'Configurations',
	CONFIRM: 'Confirmer',
    CONFIRM_IMPORT:'Confirmer l\'import ?',
    CONFIRM_IMPORT_WITH_OPTION:'Confirmer l\'import avec les options suivantes :',
	CONFIRM_PASSWORD: 'Confirmer le mot de passe',
	CONNECTED: 'Connecté',
	CONNECTING: 'Connexion ...',
    CONTAINS_OBSOLETE_PARTS:'Contient des articles obsolètes',
	CONTENT: 'Contenu',
	CONTENT_HELP: 'Contenu du ou des fichier(s)',
	CONTROLS_SHORTCUTS: 'Raccourcis clavier/souris',
	COPY: 'Copier',
    CONVERSION:'Conversion',
    CONVERSION_STATUS:'Statut de la conversion',
    CONVERSION_PENDING:'Conversion en cours',
    CONVERSION_SUCCEED:'Conversion réussie',
    CONVERSION_FAILED:'Conversion échouée',
	COWORKERS: 'Collaborateurs',
	CREATE_BASELINE: 'Créer une baseline',
	CREATE: 'Créer',
	CREATE_NEW_PART: 'Créer un nouvel article',
    CREATE_NEW_PART_AS_SUBSTITUTE: 'Créer un nouvel article comme variante',
	CREATE_NEW_VERSION: 'Créer une nouvelle version',
	CREATE_PART: 'Créer l\'article',
    CREATE_PART_SUBSTITUTE_TOOLTIP: 'Pour créer une variante, vous devez d\'abord sélectionner un lien d\'usage',
    CREATE_PART_TOOLTIP: 'Pour créer un nouveau lien d\'usage, aucun élément ne doit être sélectionné',
	CREATE_PRODUCT: 'Créer le produit',
	CREATE_ROOM: 'Démarrer une revue de maquette',
	CREATION_DATE: 'Date de création',
	CREATION_ERROR: 'Une erreur s\'est produite lors de la création',
	CURRENT_TAGS: 'Libellés associés',
	CURRENT_WORKFLOW: 'Processus métier en cours',
	CUTPLAN: 'Plan de coupe',
	DATE: 'Date',
	_DATE_FORMAT: 'DD-MM-YYYY HH:mm:ss',
	_DATE_PICKER_DATE_FORMAT: 'YYYY-MM-DD',
	_DATE_SHORT_FORMAT: 'DD-MM-YYYY',
	DATE_SORT: 'date_sort',
	DBL_CLICK: 'double clic',
	DELETE_ACTIVITY: 'Supprimer l\'activité',
	DELETE_FOLDER_QUESTION: 'Supprimer le dossier ?',
	DELETE_LINKED_ITEM: 'Supprimer le lien',
	DELETE_MARKER: 'Supprimer le marqueur',
	DELETE_PRODUCT_CONFIRM: 'Etes-vous sûr de vouloir supprimer ce produit ?',
	DELETE_PRODUCT_ERROR: 'Une erreur est survenue lors de la suppresion.',
	DELETE_PRODUCT: 'Supprimer le produit',
	DELETE_SELECTION_QUESTION: 'Supprimer la sélection ?',
	DELETE_SELECTION: 'Supprimer la sélection',
	DELETE: 'Supprimer',
	DELETE_TAG_QUESTION: 'Supprimer le libellé ?',
	DELETE_TASK: 'Supprimer la tâche',
    DELETE_QUERY_QUESTION: 'Supprimer la requête',
    DESCRIPTION: 'Description',
	DEVICE_ERROR: 'Imposible de se connecter à votre matériel audio/vidéo. Veillez à activer le WebRTC pour votre navigateur, et de vérifier les exceptions.',
    DISPLAY_COMMENTS: 'Afficher/Masquer les descriptions',
	DOCUMENT: 'Document',
    DOCUMENT_REVISION_NOTE_PROMPT_LABEL: 'Souhaitez-vous ajouter une note de révision aux documents qui n\'en ont pas ?',
    DOCUMENT_S_DESCRIPTION: 'Description du document',
    DOCUMENT_S_REFERENCE: 'Référence du document',
    DOCUMENT_S_TITLE: 'Titre du document',
    DOCUMENT_TEMPLATES: 'Modèle de document',
    DOCUMENT_TYPE_HELP: 'Type du document',
    DOCUMENT_VERSION_HELP: 'Version du document',
	DOCUMENTS: 'Documents',
    DOCUMENTS_COLLECTION: 'Collection de documents',
    DOCUMENTS_COLLECTIONS: 'Collections de documents',
	DOCUMENTS_MANAGEMENT: 'Gestion des documents',
	DOWNLOAD_DPLM_CLIENT: 'Télécharger le client DPLM',
    DOWNLOAD_ZIP:'Télécharger tous les fichiers dans un zip',
	DROP_FILE_HERE: 'ou déposez le ici',
	DROP_FILES_HERE: 'ou déposez les ici',
	DUE_DATE: 'Date d\'échéance',
	DUPLICATE: 'Dupliquer',
    DUPLICATE_WORKFLOW: 'Dupliquer le processus métier',
	EDIT_BASELINE: 'Editer la baseline',
	EDIT: 'Editer',
	EDIT_ISSUE: 'Editer l\'anomalie',
	EDIT_LINKED_DOCUMENTS: 'Editer les liens',
    EDIT_LINKED_DOCUMENT_COMMENT: 'Editer le commentaire',
	EDIT_MILESTONE: 'Editer le jalon',
	EDIT_ORDER: 'Editer l\'ordre de modification',
	EDIT_PRODUCT: 'Editer le produit',
	EDIT_PRODUCT_INSTANCE: 'Modifier l\'exemplaire',
	EDIT_REQUEST: 'Editer la demande de modification',
    EDITION_ERROR:'Une erreur est survenue pendant l\'édition',
    EMAIL:'Email',
    EMBED_SCENE: 'Exporter la scène',
    EMPTY_CHOICES:'Impossible de créer une configuration sans choix',
    EMPTY_REVISION_NOTE:'Pas de note de résivision. Ajoutez en une ou décochez cette option',
	ENTER_NAV: 'Commencer la navigation',
	ERROR: 'Erreur',
    ERRORS: 'Erreurs : ',
    ERROR_404:'Nous n\'avons pas pu trouver ce que vous cherchez ...',
    ERROR_404_SORRY:'Désolé !',
	EXISTING_TAGS: 'Libellé disponible',
	EXIT: 'Quitter la revue de maquette',
	EXPIRE_DATE: 'Date d\'expiration',
	EXPLODE: 'Eclater',
	EXPORT: 'Exporter',
    EVERYTHING: 'Tout',
	FALSE: 'Non',
    FILE: 'Fichier',
	FILE_DELETION_ERROR: 'Le fichier %{id} n\'a pu être supprimé',
    FILE_UPLOADED: 'Le fichier a bien été envoyé',
    FILES_UPLOADED: 'Les fichiers ont bien été envoyés',
	FILES: 'Fichiers',
	FILTER: 'Filtrer',
	FINAL_STATE_PLACEHOLDER: 'Etat final',
	FIRST_PAGE: 'Première page',
	FIT_VIEW: 'Centrer les objets visibles',
	FLYING_MODE: 'Mode libre',
	FLY_TO: 'Atteindre',
	FOLDER: 'Dossier',
	FOLDERS: 'Dossiers',
	FOLDER_S_NAME: 'Nom du dossier',
	FOLD_TASK: 'Réduire la tâche',
	FORBIDDEN: 'Interdit',
	FORBIDDEN_MESSAGE: 'Vous n\'avez pas accès à cette ressource, vous devez vous connecter pour continuer',
	FORM_HELPER: 'Laissez ces champs vides si vous ne voulez pas spécifier de mot de passe ou de date d\'expiration',
    FREEZE_CURRENT_ITERATION: 'Figer l\'itération en cours',
    FREEZE_AFTER_MODIFICATION: 'Geler les itérations après modifications',
    FROM:'Depuis',
	FULL_ACCESS: 'Accès complet',
	FULL_SCREEN: 'Plein écran',
	GENERAL: 'Général',
	GENERATED_URL: 'Lien généré',
	GIVE_HAND: 'Donner la main',
	GO_TO_PAGE: 'Aller à la page ...',
	GOTO_PARALLEL_MODE: 'Transformer l\'activité en parallèle',
	GOTO_SEQUENTIAL_MODE: 'Transformer l\'activité en serie',
	GRID_SWITCH: 'Afficher/Masquer la grille',
	GROUPS: 'Groupes',
    HAS_SUBSTITUTES: 'Possède des variantes',
    HEAD_CHECKIN:'Derniers libérés',
    HEAD_RELEASED:'Derniers finalisés',
    HEAD_WIP:'Travail en cours',
    HIDE_SUBSTITUTES:'Masquer les variantes',
    HOME_PAGE: 'Accueil',
    HOURS: 'h',
	HISTORY: 'Historique',
    ID_GENERATION: 'Génération de l\'id',
    IGNORE: 'Ignorer',
    IMPORT_ATTRIBUTE_FILE: 'Importer un fichier d\'attributs',
    IMPORT_DELIVERABLE_DATA:"Importer des données d'exemplaires",
    IMPORT_PART_DATA:'Importer des données d\'articles',
    IMPORT_PENDING:'Import en cours',
    IMPORT_SUCCEED:'Import réussi',
    IMPORT_FAILED:'Echec de l\'import',
    IMPORTER:'Importer un fichier',
    INIT_VALUE: 'Valeur initiale',
    IN_PROGRESS: 'En cours',
    INITIATOR: 'Initiateur',
	INSTANCE_SELECTED: 'Instance sélectionnée',
	INSTRUCTIONS: 'Instructions',
    INVERT_SOURCE_DESTINATION:'Inverser la source et la destination',
	INVITE: 'Inviter des collaborateurs',
	ISSUES: 'Anomalies',
    IS_COMPONENT_OF:'Est un composant de :',
    IS_SUBSTITUTE_IN:'Est une variante dans :',
    IS_SUBSTITUTE: 'Est une variante',
	ITERATION_CHANGE: 'Changement d\'iteration',
	ITERATION: 'Itération',
	KEYBOARD_SHORTCUTS: 'Raccourcis clavier',
	LAST_ITERATION: 'Itération courante',
	LAST_PAGE: 'Dernière page',
	LATEST: 'Dernier',
	LATEST_SHORT:'Dernières versions',
	LAYERS: 'Calques',
	LEAVE_NAV: 'Quitter la navigation',
	LEFT_CLICK: 'clic gauche',
	LIFECYCLE_STATE: 'Etat du cycle de vie',
    LINK_DESCRIPTION: 'Description du lien',
    LINKED_DOCUMENTS: 'Documents liés',
    LINKS: 'Liens',
    LIST_LOV:'Ensemble des listes de valeurs',
    LOV:'Liste de valeurs',
    LOADING:'Chargement',
    LOCK:'Verrouiller',
	LOCK_ATTRIBUTES: 'Geler la structure des attributs',
	LOCKED: 'Verrouillé',
    LOGIN:'Identifiant',
	LOGOUT: 'Se déconnecter',
	LOOK_AT: 'Regarder',
	MANAGE_PRODUCT: 'Gestion des produits',
	MANAGE_ROLES: 'Gestion des rôles',
	MANDATORY: 'Obligatoire',
    MARK_ALL_AS_VERIFIED: 'Marquer tout comme vérifié',
    MARK_AS_VERIFIED: 'Marquer comme vérifié',
    MARK_AS_OBSOLETE: 'Marquer ces articles comme obsolètes',
    MARK_DOCUMENT_AS_OBSOLETE_QUESTION: 'Marquer le document sélectionné comme obsolète ?',
    MARK_PART_AS_OBSOLETE_QUESTION: 'Marquer l\'article sélectionné comme obsolète ?',
    MARKER_INFO: 'Afficher des informations sur la note',
	MARKERS: 'Marqueurs',
	MARKERS_OPACITY: 'Changer l\'opacité des marqueurs',
	MARKERS_SIZE_MAX: 'Augmenter la taille des marqueurs',
	MARKERS_SIZE_MIN: 'Diminuer la taille des marqueurs',
	MASK_HELP: 'Définissez le format de la référence des documents/articles créés avec ce modèle.</br></br>En plus des caractères ordinaires, vous pouvez utiliser \'#\' pour tout chiffre valide et \'*\' pour n\'importe quel caractère.</br></br>Par exemple \'FAX_***_##\' accepte \'FAX-AZE-12\' comme entrée valide pour la référence.<br /><br /> Un masque sans caractère \'*\' ou \'#\' ne sera utilisable qu\'une fois',
	MASK: 'Masque',
	MEASURE: 'Mesure',
	MILESTONE: 'Jalon',
	MILESTONES: 'Jalons',
	MODIFICATION_DATE: 'Date de modification',
    MODIFICATION_NOTIFICATION_LIST_DESCRIPTION: 'Journal des modifications des sous-composants',
    MOUSE_CONTROLS: 'Contrôles de la souris',
	MOVE: 'Déplacer',
	MOVE_BACKWARD: 'Reculer',
	MOVE_DOWN: 'Descendre',
	MOVE_FORWARD: 'Avancer',
	MOVE_LEFT: 'Déplacer à droite',
	MOVE_RIGHT: 'Déplacer à gauche',
	MOVE_SCENE: 'Se déplacer dans la scène',
	MOVE_UP: 'Monter',
	MY_ACCOUNT: 'Mon compte',
	MY_ORGANIZATION: 'Mon organisation',
	MY_WORKSPACES: 'Mes espaces de travail',
	NAME: 'Nom',
	NAVIGATION: 'Navigation',
	NB_TASKS_TO_COMPLETE: 'tâches à compléter',
	NEW_BASELINE: 'Nouvelle baseline',
    NEW_CONFIGURATION:'Nouvelle configuration',
	NEW_DOCUMENT: 'Nouveau document',
    NEW_DOCUMENTS_COLLECTION: 'Nouvelle collection de documents',
	NEW_FOLDER: 'Nouveau dossier',
	NEW_ISSUE: 'Nouveau rapport d\'anomalie',
    NEW_LAYER: 'Nouveau calque',
    NEW_LINK_TYPE: 'Créer un nouveau type',
	NEW_MARKER: 'Créer un marqueur',
	NEW_MILESTONE: 'Nouveau jalon',
	NEW_ORDER: 'Nouvel ordre de modification',
	NEW_PART: 'Nouvel article',
	NEW_PART_TEMPLATE: 'Nouveau modèle d\'article',
	NEW_PRODUCT_INSTANCE: 'Nouvel exemplaire',
	NEW_PRODUCT: 'Nouveau produit',
	NEW_REQUEST: 'Nouvelle demande de modification',
	NEW_ROLE: 'Nouveau rôle',
	NEW_TAG: 'Nouveau libellé',
	NEW_TEMPLATE: 'Nouveau modèle de document',
    NEW_UNIT:'Unité',
	NEW_VERSION: 'Nouvelle version',
	NEW_VERSION_OF: 'Nouvelle version de',
	NEW_WORKFLOW: 'Nouveau processus métier',
	NEXT_PAGE: 'Page suivante',
	NO_CONVERSION: 'Pas de conversion',
    NO_COWORKERS:'Aucun collaborateur',
	NO_DATA: 'Aucune donnée dans la table',
    NO_FILE_TO_IMPORT:'Pas de fichier à importer',
	NO_FILTERED_DATA: 'Aucune donnée correspondante',
	NO_LAYERS: 'Aucun calque',
	NO_PARTICIPANT: 'Aucun participant. Invitez des utilisateurs depuis le menu Collaborateurs.',
	NOTIFICATIONS: 'Notifications',
	NOT_INVITED_COLLABORATIVE_ROOM:'Vous n\'êtes pas invité à rejoindre cette salle',
    NOT_VERIFIED: 'Non vérifié',
	NO_WEBGL: 'Le navigateur ne supporte pas WebGL ou n\'est pas activé.',
    NOT_YET_REGISTERED_QUESTION:'Pas encore enregistré ?',
    NOT_YET_REGISTERED_REGISTER:'Inscrivez-vous !',
    NODE_ASSEMBLIES_VISITED:'Assemblages visités',
    NODE_INSTANCES_VISITED:'Instances visitées',
    NONE:'Aucun(e)',
	NUMBER: 'Nombre',
	OBSOLETE: 'Obsolète',
    OBSOLETE_AUTHOR: 'Rendu obsolète par',
    OBSOLETE_DATE: 'Obsolète depuis',
    OFFICIAL_SITE:'Communauté PLM',
	OFFLINE: 'Hors ligne',
	OK: 'OK',
    ON: 'le',
    OR: 'ou',
	ONLINE: 'En ligne',
	OPEN_NEW_WINDOW:'Ouvrir dans une nouvelle fenêtre',
    OPTIONAL:'Facultatif',
    OPTIONAL_REMOVE:'Aucun',
    OPTIONS: 'Options',
	OR_ADD_PART: 'Ou ajouter un article existant',
	ORBIT_MODE: 'Mode orbit',
	ORDERS_NUMBER: 'Ordres associés',
	ORDERS: 'Ordres',
	OTHERS: 'Autres',
	PARALLEL_ACTIVITY: 'En parallèle, nécessite',
    PART_ATTRIBUTES: 'Attributs de l\'article',
    PART_ATTRIBUTES_TEMPLATES: 'Modèles d\'attributs associés à l\'article',
	PARTICIPANT: 'Participant',
	PART_NAME: 'Nom',
    PART_NOT_FOUND: 'L\'article de tête n\'a pas été trouvé',
	PART_NUMBER_HELP: 'Numéro de l\'article',
	PART_NUMBER: 'Numéro',
	PARTS: 'Articles',
    PART_REVISION_NOTE_PROMPT_LABEL: 'Souhaitez-vous ajouter une note de révision aux articles qui n\'en ont pas ?',
    PART_SEARCH_HELP: 'texte',
    PART_SUBSTITUTE: 'article variante',
    PARTS_SUBSTITUTES: 'articles variantes',
    PART_TEMPLATE: 'Modèle d\'article',
	PART_TEMPLATES: 'Modèles',
	PART_TYPE_HELP: 'Type de l\'article',
    PART_VERSION_HELP: 'Version de l\'article',
	PASSWORD: 'Mot de passe',
	PASSWORD_NOT_CONFIRMED: 'Les champs mot de passe et confirmation doivent être identiques',
	PATH: 'Dossier',
    PATH_TO_PATH_LINKS:'Liens typés',
    PATH_TO_PATH_SOURCE: 'Source',
    PATH_TO_PATH_TARGET: 'Destination',
    PATH_TO_PATH_SOURCE_LINK: 'Liens source',
    PATH_TO_PATH_TARGET_LINK: 'Liens destination',
	PENDING: 'Participant absent',
	PERMALINK: 'Permalien',
    PERMISSIVE_UPDATE: 'Mise à jour permissive',
    PERMISSIVE_UPDATE_PATH_DATA:'Mise à jour permissive (seules les données d\'exemplaires modifiables seront considérées)',
    PERMISSIVE_UPDATE_PART:'Mise à jour permissive (seuls les articles modifiables seront considérés)',
    POSSIBLE_VALUE: 'valeurs possibles',
	PREVIOUS_PAGE: 'Page précédente',
	PRIVATE_SHARE_TITLE: 'Accès privé',
	PRODUCT: 'Produit',
	PRODUCT_ID: 'Référence',
	PRODUCT_INSTANCE: 'Exemplaire',
	PRODUCT_INSTANCES: 'Exemplaires',
    PRODUCT_INSTANCE_DATA: 'Données de l\'exemplaire',
    PRODUCT_INSTANCE_DATA_ATTRIBUTES: 'Attributs des données dans l\'exemplaire',
    PRODUCT_INSTANCE_DATA_ATTRIBUTES_TEMPLATES: 'Modèles d\'attributs associés aux données dans l\'exemplaire',
    PRODUCT_NAME: 'Nom de produit',
	PRODUCTS_MANAGEMENT: 'Gestion des produits',
	PRODUCTS: 'Produits',
	PRODUCT_STRUCTURE: 'Structure du produit',
    PROTECTED_RESOURCE : 'Cette resource est protégée par mot de passe',
	PUBLIC_ACCESS_TITLE: 'Accès public au permalien',
	PUBLIC_SHARE: 'Partage public',
	PUBLISH: 'Publier',
    QUERY_EXPORT_EXCEL_LOADING:'Export...',
    QUERY_EXPORT_EXCEL:'Export Excel',
	QUICK_SEARCH: 'Recherche rapide',
    QUERY_STANDARD: 'Standard',
    QUERY_BUILDER_CONDITION_AND:'ET',
    QUERY_BUILDER_CONDITION_OR:'OU',
    QUERY_BUILDER_OPERATORS_EQUALS:'égal',
    QUERY_BUILDER_OPERATORS_NOT_EQUALS:'non égal',
    QUERY_BUILDER_OPERATORS_IN:'dans',
    QUERY_BUILDER_OPERATORS_NOT_IN:'pas dans',
    QUERY_BUILDER_OPERATORS_LESS:'inférieur',
    QUERY_BUILDER_OPERATORS_LESS_OR_EQUAL:'inférieur ou égal',
    QUERY_BUILDER_OPERATORS_GREATER:'supérieur',
    QUERY_BUILDER_OPERATORS_GREATER_OR_EQUAL:'supérieur ou égal',
    QUERY_BUILDER_OPERATORS_BETWEEN:'entre',
    QUERY_BUILDER_OPERATORS_BEGIN_WITH:'commence par',
    QUERY_BUILDER_OPERATORS_NOT_BEGIN_WITH:'ne commence pas par',
    QUERY_BUILDER_OPERATORS_CONTAINS:'contient',
    QUERY_BUILDER_OPERATORS_NOT_CONTAINS:'ne contient pas',
    QUERY_BUILDER_OPERATORS_ENDS_WITH:'finit par',
    QUERY_BUILDER_OPERATORS_NOT_ENDS_WITH:'ne finit pas par',
    QUERY_BUILDER_OPERATORS_IS_EMPTY:'est vide',
    QUERY_BUILDER_OPERATORS_IS_NOT_EMPTY:'n\'est pas vide',
    QUERY_BUILDER_OPERATORS_IS_NULL:'est nul',
    QUERY_BUILDER_OPERATORS_IS_NOT_NULL:'n\'est pas nul',
    QUERY_BUILDER_ERRORS_NO_FILTER:'Aucun filtre sélectionné',
    QUERY_BUILDER_ERRORS_EMPTY_GROUP:'Le groupe est vide',
    QUERY_BUILDER_ERRORS_RADIO_EMPTY:'Pas de valeur selectionnée',
    QUERY_BUILDER_ERRORS_CHECKBOX_EMPTY:'Pas de valeur selectionnée',
    QUERY_BUILDER_ERRORS_SELECT_EMPTY:'Pas de valeur selectionnée',
    QUERY_BUILDER_ERRORS_STRING_EMPTY:'Valeur vide',
    QUERY_BUILDER_ERRORS_STRING_EXCEED_MIN_LENGTH:'Doit contenir au moins {0} caractères',
    QUERY_BUILDER_ERRORS_STRING_EXCEED_MAX_LENGTH:'Ne doit pas contenir plus de {0} caractères',
    QUERY_BUILDER_ERRORS_STRING_INVALID_FORMAT:'Format invalide ({0})',
    QUERY_BUILDER_ERRORS_NUMBER_NAN:'N\'est pas un nombre',
    QUERY_BUILDER_ERRORS_NUMBER_NOT_INTEGER:'N\'est pas un entier',
    QUERY_BUILDER_ERRORS_NUMBER_NOT_DOUBLE:'N\'est pas un nombre réel',
    QUERY_BUILDER_ERRORS_NUMBER_EXCEED_MIN:'Doit être plus grand que {0}',
    QUERY_BUILDER_ERRORS_NUMBER_EXCEED_MAX:'Doit être plus petit que {0}',
    QUERY_BUILDER_ERRORS_NUMBER_WRONG_STEP:'Doit être un multiple de {0}',
    QUERY_BUILDER_ERRORS_DATETIME_EMPTY:'Valeur vide',
    QUERY_BUILDER_ERRORS_DATETIME_INVALID:'Fomat de date invalide ({0})',
    QUERY_BUILDER_ERRORS_DATETIME_EXCEED_MIN:'Doit être après {0}',
    QUERY_BUILDER_ERRORS_DATETIME_EXCEED_MAX:'Doit être avant {0}',
    QUERY_BUILDER_ERRORS_BOOLEAN_NOT_VALID:'N\'est pas un booléen',
    QUERY_BUILDER_ERRORS_OPERATOR_NOT_MULTIPLE:'L\'opérateur {0} ne peut utiliser plusieurs valeurs',
    QUERY_GROUP_AUTHOR:'Auteur',
    QUERY_GROUP_PART_MASTER:'Article',
    QUERY_GROUP_PART_REVISION:'Revision d\'article',
    QUERY_GROUP_PRODUCT:'Produit',
    QUERY_GROUP_ATTRIBUTE_STRING:'Attribut de type chaine',
    QUERY_GROUP_ATTRIBUTE_LONG_STRING:'Attribut de type longue chaine',
    QUERY_GROUP_ATTRIBUTE_URL:'Attribut de type URL',
    QUERY_GROUP_ATTRIBUTE_LOV:'Attribut de type Liste de valeurs',
    QUERY_GROUP_ATTRIBUTE_NUMBER:'Attribut de type nombre',
    QUERY_GROUP_ATTRIBUTE_DATE:'Attribut de type date',
    QUERY_GROUP_ATTRIBUTE_BOOLEAN:'Attribut de type booléen',
    QUERY_GROUP_CONTEXT:'Contexte',
    QUERY_GROUP_PATH_DATA_ATTRIBUTE:'Attribut d\'exemplaire',
    QUERY_NAME:'Nom de la requête',
    QUERY_SEARCH:'Construire une requête',
    QUERY_SELECT:'Champs',
    QUERY_CONTEXT:'Contexte',
    QUERY_WHERE:'Critères',
    QUERY_ORDER_BY:'Ordonner par',
    QUERY_GROUP_BY:'Grouper par',
    QUERY_CLEAR:'vider',
    QUERY_CHOOSE_EXISTING_REQUEST:'Ou utiliser une requête sauvegardée...',
    QUERY_REMOVE_SAVED_QUERY:'Supprimer de la liste des requêtes',
    QUERY_CONTEXT_ERROR:'Impossible de récuperer la liste des produits',
    QUERY_ATTRIBUTES_ERROR:'Impossible de récuperer la liste des attributs',
    QUERY_FILTER_STATUS_WIP:'Travail en cours',
    QUERY_FILTER_STATUS_RELEASED:'Finalisé',
    QUERY_FILTER_STATUS_OBSOLETE:'Obsolète',
    QUERY_DEPTH:'Profondeur',
	READ_ONLY: 'Lecture seule',
    REBASE: 'Rebaser',
    REBASE_AUTHOR: 'Auteur de l\'itération',
    REBASE_SUCCESS: 'L\'exemplaire a bien été rebasé',
	REFERENCE_HELP: 'ID du document',
	REFERENCE: 'Référence',
    REFRESH_TREE : 'Rafraîchir l\'arbre',
	REJECT_TASK: 'Rejeter la tâche',
	REJECT_VIDEO_INVITE: 'Rejeter',
	RELAUCNH_ACTIVITY_SELECTOR: 'Retour à l\'activité en cas de rejet',
	RELEASED: 'Finalisé',
	RELEASED_SHORT:'Dernières versions finalisées',
	RELEASE: 'Finaliser',
    RELEASE_DATE: 'Finalisé depuis',
    RELEASED_BY: 'Finalisé par',
	RELEASE_NOW: 'Finaliser maintenant',
	RELEASE_SELECTION_QUESTION: 'Finaliser la sélection ?',
    RELOAD:'Recharger',
	REMOTE_ACCEPT: 'L\'utilisateur distant a accepté l\'appel. En attente de connexion ...',
	REMOTE_BUSY: 'L\'utilisateur distant est occupé. Appel terminé ...',
	REMOTE_HANGUP: 'L\'utilisateur distant a raccroché',
	REMOTE_OFFLINE: 'L\'utilisateur distant est hors-ligne. Appel terminé ...',
	REMOTE_REJECT: 'L\'utilisateur distant a rejeté l\'appel. Appel terminé ...',
	REMOTE_STEAM_ADDED: 'Flux vidéo de l\'utilisateur distant ajouté',
	REMOTE_STEAM_REMOVED: 'Flux vidéo de l\'utilisateur distant enlevé',
	REMOTE_TIMEOUT: 'L\'utilisateur distant n\'a pas répondu à temps. Appel terminé ...',
	RENAME: 'Renommer',
	RENAME_WORKFLOW_COPY: 'Nom de la copie',
	REPLACE: 'Réinitialiser',
	REQUESTS: 'Demandes',
	REQUESTS_NUMBER: 'Demandes associées',
    REQUIRED_FIELD:'Veuillez renseigner ce champ',
    RESET: 'Remise à zero',
    RESET_CAMERA: 'Repositionner la caméra',
    RESULT:'Résultat',
    RETAIN: 'Retenir',
    RETRY: 'Re-essayer',
    REVISION_DATE: 'Date de révision',
	REVISION_NOTE: 'Note de révision',
	REVISION_NOTE_PROMPT_CANCEL: 'Ignorer',
	REVISION_NOTE_PROMPT_LABEL: 'Souhaitez-vous ajouter une note de révision ?',
	REVISION_NOTE_PROMPT_OK: 'Ajouter la note de révision',
	RIGHT_CLICK: 'clic droit',
	ROLE_NAME: 'Nom du rôle',
	ROLE: 'Rôle',
	ROLES: 'Rôles',
	ROOT_PART: 'Article de tête',
	ROTATE: 'Rotation',
	ROTATE_SCENE: 'Pivoter la scène',
    RUN:'Lancer',
	SAVED: 'Sauvegardé',
	SAVE: 'Enregistrer',
	SCALE: 'Echelle',
	SCENE_VIEW: 'Scène',
	SCROLL_DOWN: 'défilement bas',
	SCROLL_UP: 'défilement haut',
	SEARCH_OPTIONS: 'Options de recherche par numéro ou nom',
	SEARCH_PART_BEGINNING: 'Article commencant par',
	SEARCH_PART_CALLED: 'Rechercher l\'article',
	SEARCH_PART_ENDING: 'Article finissant par',
	SEARCH_PARTS: 'Recherche d\'articles',
	SEARCH: 'Rechercher',
    SEARCHING: 'Recherche en cours...',
    SEARCHING_FOR_PARTS: "Recherche des articles en cours, veuillez ne pas fermer la fenêtre...",
    SECONDS: 's',
    SEE_IN_DOCUMENT_MANAGEMENT:'Voir le document dans la gestion des documents',
    SEE_IN_PRODUCT_MANAGEMENT:'Voir l\'article dans la gestion des produits',
    SELECT_FILE: 'Choisissez un fichier',
	SELECT_FILES: 'Choisissez un ou plusieurs fichier(s)',
	SEND: 'Envoyer',
    SEQUENTIAL_ACTIVITY: 'En série',
	SERIAL_NUMBER: 'Numéro de série',
	SESSION_CONNECTING: 'Connexion de la session ...',
	SESSION_OPENED: 'Session connectée',
	SHARED_DOCUMENTS_TITLE: 'Publier le document',
	SHARED_PARTS_TITLE: 'Publier l\'article',
	SHARE: 'Partager',
	SHORTCUTS_TITLE: 'Raccourcis clavier / souris',
    SHOW_ALL: 'Tout voir',
    SHOW_BY_PAGE: 'Voir par page',
	SHOW_EDITED_MESHES: 'Surligner les objets modifiés',
    SHOW_SUBSTITUTES:'Afficher les variantes',
	SIGN_TASK: 'Signature',
    SINGLE_FILE_RESTRICTION:'Seulement un fichier est autorisé.',
	SPACE: 'espace',
	STANDARD_PART_ALL: 'Tous',
	STANDARD_PART: 'Article standard',
	STANDARD_PART_FALSE: 'Non',
	STANDARD_PART_TRUE: 'Oui',
	START: 'Départ',
    START_IMPORT: 'Lancer l\'import',
	STATE_CHANGE: 'Changement d\'état',
	STATUS: 'Statut',
    STRUCTURE: 'Structure',
    SUB_PARTS: 'Assemblage',
	SUBSCRIBE_ITERATION_CHANGE: 'S\'abonner aux notifications de changement d\'itération',
	SUBSCRIBE_STATE_CHANGE: 'S\'abonner aux notifications de changement d\'état',
    SUM:'Somme',
    TAGS_HELP: 'Liste des libéllés, séparés par une virgule',
	TAGS: 'Libellés',
	TAGS_TO_ADD: 'Libellés à ajouter',
	TAKE_SCREENSHOT: 'Capture d\'écran',
	TASK_APPROVED_ON: 'Tâche effectuée le',
	TASK_CLOSED_ON: 'Tâche fermée le',
	TASK_NAME_PLACEHOLDER: 'Nouvelle tâche',
	TASK_REJECT_ON: 'Tâche rejetée le',
    TASK_WORKER: 'Effectué par',
	TASKS_IN_PROGRESS: 'En cours',
	TASKS: 'Tâches',
	TEMPLATE: 'Modèle',
	TEMPLATES: 'Modèles',
	TEXT: 'Texte',
    LONG_TEXT: 'Texte long',
	TITLE_HELP: 'Titre du document',
	TITLE: 'Titre',
    TO:'Au',
	TOGGLE_ALL_LAYERS: 'Basculer la visibilité des calques',
	TRACKBALL_MODE: 'Mode trackball',
	TRANSFORM_CONTROLS: 'Transformation',
	TRUE: 'Oui',
	TYPE: 'Type',
    UDF_DEF:'Fonction',
    UNCHECK_ALL: 'Tout désélectionner',
	UNDO_CHECKOUT: 'Annuler la réservation',
	UNDO_CHECKOUT_QUESTION: 'Annuler la réservation ?',
	UNFOLD_TASK: 'Editer la tâche',
	UNREACHABLE: 'Impossible d\'envoyer l\'invitation, l\'utilisateur distant est hors-ligne',
	UNSUBSCRIBE_ITERATION_CHANGE: 'Se désabonner des notifications de changement d\'itération',
	UNSUBSCRIBE_STATE_CHANGE: 'Se désabonner des notifications de changement d\'état',
	UNIT: 'unité',
    UPDATE_ACL_ERROR:'Une erreur s\'est produite pendant la mise à jour des droits',
	URL: 'URL',
	USE_ACL: 'Utiliser les ACL (droits) ?',
    USER_DEFINED_FUNCTION:'Fonction utilisateur',
	USER_MEDIA_FAILED: 'Imposible d\'accéder à votre entrée vidéo. Votre navigateur supporte-il le WebRTC ?',
	USERS_CONNECTED: 'utilisateurs connectés',
	USERS: 'Utilisateurs',
	VALIDATION_FAILED_FOR: 'Validation échouée pour ',
	_VALIDATION_PATTERN_DATE: '\\d{4}-\\d{2}-\\d{2}',
    _VALIDATION_PATTERN_NUMBER: '^\\-?\\d+(\\.\\d+)?(([eE]([-+])?)?\\d+)?$',
	_VALIDATION_PATTERN_TIME: '\\d{2}:\\d{2}',
	VALUE: 'Valeur',
    VALUES: 'Valeurs',
    VERIFICATION_NOTE: 'Note de vérification',
    VERIFIED: 'Vérifié',
	VERSION: 'Version',
	VERSIONS: 'Versions',
	VIDEO_INVITATION_SENT: 'L\'invitation a été envoyée à l\'utilisateur distant, en attente de l\'acceptation ...',
	VIDEO_INVITE_ACCEPT: 'Accepter',
	VIDEO_INVITE_NOTIFICATION_TITLE: 'Invitation Vidéo',
	VIDEO_INVITE_REJECT: 'Refuser',
	VIDEO_INVITE_TEXT: 'vous invite à démarrer une session vidéo.',
	VIEW_MODE: 'Mode de vue',
	VISUALIZE_ASSEMBLY: 'Visualiser l\'assemblage',
	VISUALIZE_PRODUCT: 'Visualiser le produit',
	WAITING_REMOTE_VIDEO: 'En attente de la vidéo de l\'utilisateur distant.',
	WAITING_USER_MEDIA: 'En attente de l\'entrée vidéo ... Veuillez accepter la demande de votre navigateur.',
    USED_BY: 'Cas d\'emploi',
    WARNINGS:'Avertissements : ',
	WITHDRAW_INVITATION: 'Retirer l\'invitation',
    WITH_LINKS: 'Avec les liens',
    WITHOUT_LINKS: 'Sans les liens',
	WORKFLOW_HISTORY: 'Historique',
	WORKFLOW_LEGEND_COMPLETE: 'Complet',
	WORKFLOW_LEGEND_INCOMPLETE: 'Incomplet',
	WORKFLOW_LEGEND_INPROGRESS: 'En cours',
	WORKFLOW_LEGEND_REJECTED: 'Rejeté',
	WORKFLOW_NAME_PLACEHOLDER: 'Nom du processus métier',
    WORKFLOW: 'Processus',
    WORKFLOW_COPY: 'Copie du processus',
	WORKFLOWS: 'Processus',
	WORKSPACE: 'Espace de travail',
	WORKSPACES_ADMINISTRATION: 'Administration des espaces de travail',
    WORKSPACE_MANAGEMENT: 'Administration de l\'espace',
	WORKSPACES: 'Workspaces',
    YOU_CANNOT_CREATE_LINK_WITHOUT_TYPE: 'Vous ne pouvez pas créer un lien sans type',
	YOU_HAVE_BEEN_KICKED:'Vous avez été exclu de la salle collaborative',
    LANGUAGES:{
        fr:'Français',
        en:'Anglais'
    }
});
