#! /usr/bin/env sh

PRG="$0"
while [ -h "$PRG" ] ; do
    PRG=`readlink "$PRG"`
done
dir=`dirname $PRG`

java -classpath $dir/target/docdoku-cli-jar-with-dependencies.jar com.docdoku.cli.commands.MainCommand $@
