#! /usr/bin/env sh

PRG="$0"
while [ -h "$PRG" ] ; do
    PRG=`readlink "$PRG"`
done
dir=`dirname $PRG`

jjs --language=es6 -scripting -J-Xmx1024M -classpath $dir/target/docdoku-cli-jar-with-dependencies.jar $@
