#! /usr/bin/env sh

PRG="$0"
while [ -h "$PRG" ] ; do
    PRG=`readlink "$PRG"`
done
dir=`dirname $PRG`

/home/morgan/java7/jdk1.7.0_11/bin/java -Xmx1024M -classpath $dir/target/docdoku-cli-jar-with-dependencies.jar com.docdoku.cli.MainCommand $@
