/*global define*/
define({
    ALL: 'Tous',
    BASELINE_OF: 'Baseline de',
    DUPLICATE_BASELINE: 'Dupliquer la baseline',
    EDIT_BASELINE: 'Editer la baseline',
    EXCLUDE: 'Exclure l\'article de la baseline',
    NEW_BASELINE: 'Nouvelle baseline',
    SEND: "Envoyer",
    VIDEO_INVITE_ACCEPT: "Accepter",
    VIDEO_INVITE_REJECT: "Refuser",
    COLLABORATIVE_INVITE: "Vous êtes invité à rejoindre une salle collaborative",
    COLLABORATIVE_WITHDRAW_INVITATION: "Invitation annulée",
    ONLINE: "En ligne",
    OFFLINE: "Hors ligne",
    NO_DATA: "Aucune donnée dans la table",
    NO_FILTERED_DATA: "Aucune donnée correspondante",
    DATE_SORT: "date_sort_fr",
    ATTACHED_FILES: "Fichiers",
    SELECT_FILE: "Choisissez un fichier",
    DROP_FILE_HERE: "ou déposez un fichier ici",
    BOOLEAN: "Booléen",
    DATE: "Date",
    DELETE_FOLDER_QUESTION: "Supprimer le dossier ?",
    DELETE_TAG_QUESTION: "Supprimer le libellé ?",
    DOCUMENT: "Document",
    DOCUMENT_S_DESCRIPTION: "Description du document",
    DOCUMENT_S_REFERENCE: "Référence du document",
    DOCUMENT_S_TITLE: "Titre du document",
    EDIT: "Editer",
    FOLDER: "Dossier",
    FOLDERS: "Dossiers",
    FOLDER_S_NAME: "Nom du dossier",
    HISTORY: "Historique",
    LAST_ITERATION: "Itération courante",
    NEW_DOCUMENT: "Nouveau document",
    NEW_FOLDER: "Nouveau dossier",
    NEW_TAG: "Nouveau libellé",
    NEW_TEMPLATE: "Nouveau modèle de document",
    NEW_WORKFLOW: "Nouveau workflow",
    NUMBER: "Nombre",
    OK: "OK",
    REFERENCES: "Objets",
    RENAME: "Renommer",
    REVISION_NOTE_PROMPT_LABEL: "La note de révision n'a pas été définie. Souhaitez-vous l'ajouter ?",
    REVISION_NOTE_PROMPT_CANCEL: "Ignorer",
    REVISION_NOTE_PROMPT_OK: "Ajouter la note de révision",
    SAVED: "Sauvegardé",
    COPY: "Copier",
    TAGS: "Libellés",
    TASKS: "Tâches",
    TEMPLATE: "Modèle",
    TEMPLATES: "Modèles",
    TEXT: "Texte",
    URL: "URL",
    VALUE: "Valeur",
    WORKFLOWS: "Workflows",
    COPY_WORKFLOW: "Copier le workflow",
    WORKFLOW_NAME_PLACEHOLDER: "Nom du nouveau workflow",
    RENAME_WORKFLOW_COPY: "Nom de la copie",
    ADD_ACTIVITY: "Ajouter une activité",
    GOTO_SERIAL_MODE: "Transformer l'activité en serie",
    GOTO_PARALLEL_MODE: "Transformer l'activité en parallèle",
    NB_TASKS_TO_COMPLETE: "tâches à compléter",
    ACTIVITY_STATE_PLACEHOLDER: "Nouvel état",
    START: "Départ",
    FINAL_STATE_PLACEHOLDER: "Etat final",
    DELETE_ACTIVITY: "Supprimer l'activité",
    ADD_TASK: "Ajouter une tâche",
    UNFOLD_TASK: "Editer la tâche",
    FOLD_TASK: "Réduire la tâche",
    TASK_NAME_PLACEHOLDER: "Nouvelle tâche",
    DELETE_TASK: "Supprimer la tâche",
    INSTRUCTIONS: "Instructions",
    ROLE: "Rôle",
    WORKSPACES: "Workspaces",
    VALIDATION_FAILED_FOR: "Validation échouée pour ",
    ADD_NEW_TAG: "Saisir un nouveau libellé",
    XISTING_TAGS: "Libellés disponibles",
    CURRENT_TAGS: "Libellés associés",
    TAGS_TO_ADD: "Libellés à ajouter",
    NOTIFICATIONS: "Notifications",
    SUBSCRIBE_STATE_CHANGE: "S'abonner aux notifications de changement d'état",
    UNSUBSCRIBE_STATE_CHANGE: "Se désabonner des notifications de changement d'état",
    SUBSCRIBE_ITERATION_CHANGE: "S'abonner aux notifications de changement d'itération",
    UNSUBSCRIBE_ITERATION_CHANGE: "Se désabonner des notifications de changement d'itération",
    ITERATION_CHANGE: "Changement d'iteration",
    STATE_CHANGE: "Changement d'état",
    ADVANCED: "Avancé",
    REFERENCE_HELP: "ID du document",
    TITLE_HELP: "Titre du document",
    TAGS_HELP: "Liste des libéllés, séparés par une virgule",
    CONTENT: "Contenu",
    CONTENT_HELP: "Contenu du document",
    COMMENT: "Commentaire",
    SERIAL_ACTIVITY: "En série",
    PARALLEL_ACTIVITY: "En parallèle, nécessite",
    TASK_CLOSED_ON: "Tâche fermée le",
    TASK_APPROVED_ON: "Tâche effectuée le",
    TASK_REJECT_ON: "Tâche rejetée le",
    APPROVE_TASK: "Marquer la tâche comme effectuée",
    REJECT_TASK: "Rejeter la tâche",
    CLOSURE_COMMENT: "Commentaire",
    DELETE_LINKED_ITEM: "Supprimer le lien",
    EDIT_LINKED_DOCUMENTS: "Editer les liens",
    ADD_DOCUMENT: "Ajouter un document",
    SIGN_TASK: "Signature",
    MASK_HELP: "D\u00e9finissez le format de la r\u00e9f\u00e9rence des documents/articles cr\u00e9\u00e9s avec ce mod\u00e8le.</br></br>En plus des caract\u00e8res ordinaires, vous pouvez utiliser '#' pour tout nombre valide et '*' pour n'importe quel caract\u00e8re.</br></br>Par exemple 'FAX_***_##' accepte 'FAX-AZE-12' comme entr\u00e9e valide pour la r\u00e9f\u00e9rence.",
    CLEAR: "Effacer",
    PATH: "Dossier",
    FILTER: "Filtrer",
    RELAUCNH_ACTIVITY_SELECTOR: "Retour à l'activité en cas de rejet",
    WORKFLOW_HISTORY: "Historique",
    CURRENT_WORKFLOW: "Workflow en cours",
    WORKFLOW_LEGEND_INCOMPLETE: "Incomplet",
    WORKFLOW_LEGEND_COMPLETE: "Complet",
    WORKFLOW_LEGEND_REJECTED: "Rejeté",
    WORKFLOW_LEGEND_INPROGRESS: "En cours",
    ALL_TASKS: "Toutes",
    TASKS_IN_PROGRESS: "En cours",
    MY_WORKSPACES: 'Mes espaces de travail',
    ADMINISTRATED: 'Administrés',
    OTHERS: 'Autres',
    DOCUMENTS_MANAGEMENT: 'Gestion des documents',
    PRODUCTS_MANAGEMENT: 'Gestion des produits',
    CHANGES_MANAGEMENT: 'Gestion des changements',
    DOCUMENTS: 'Documents',
    CHANGES: 'Gestion des changements',
    COWORKERS: 'Collaborateurs',
    MY_ACCOUNT: 'Mon compte',
    MY_ORGANIZATION: 'Mon organisation',
    WORKSPACES_ADMINISTRATION: 'Administration des espaces de travail',
    DOWNLOAD_DPLM_CLIENT: 'Télécharger le client DPLM',
    ABOUT_DOCDOKUPLM: 'A propos de DocdokuPLM',
    LOGOUT: 'Se déconnecter',
    CREATE_PRODUCT: "Créer le produit",
    CREATE_PART: "Créer l'article",
    DELETE_PRODUCT: "Supprimer le produit",
    ROOT_PART_NUMBER: "Numéro de l'article de tête",
    CANCEL_PART_CREATION: "Annuler la création de l'article",
    MANAGE_PRODUCT: "Gestion des produits",
    ALL_PRODUCTS: "Tous les produits",
    EDIT_PRODUCT: "Editer le produit",
    DELETE_PRODUCT_CONFIRM: "Etes-vous sûr de vouloir supprimer ce produit ?",
    DELETE_PRODUCT_ERROR: "Une erreur est survenue lors de la suppresion.",
    VISUALIZE_PRODUCT: "Visualiser le produit",
    LOCK_ATTRIBUTES: "Geler la structure des attributs",
    MANDATORY: "Obligatoire",
    _DATE_SHORT_FORMAT: "dd-mm-yyyy",
    _DATE_PICKER_DATE_FORMAT: "yyyy-mm-dd",
    _VALIDATION_PATTERN_DATE: "\\d{4}-\\d{2}-\\d{2}",
    _VALIDATION_PATTERN_NUMBER: "^\\-?\\d+(\\.\\d+)?$",
    _VALIDATION_PATTERN_TIME: "\\d{2}:\\d{2}",
    BASELINE: "Baseline",
    CHOOSE_A_PRODUCT: "S\u00e9lectionnez un produit",
    CREATION_ERROR: "Une erreur s'est produite lors de la création",
    EDIT_PRODUCT_INSTANCE: "Modifier l'exemplaire",
    NEW_PRODUCT_INSTANCE: "Nouvel exemplaire",
    PRODUCT_INSTANCES: "Exemplaires",
    SERIAL_NUMBER: "Num\u00e9ro de s\u00e9rie",
    UPDATE_AUTHOR: "Auteur de la mise \u00e0 jour",
    UPDATE_DATE: "Date de la mise \u00e0 jour",
    ADD_PART: "Ajouter un article",
    ADVANCED_SEARCH: "Recherche avanc\u00e9e",
    AUTHOR_PART_HELP: "Auteur de l'article",
    AUTHOR_DOCUMENT_HELP: "Auteur du document",
    BASELINES: "Baselines",
    CREATE: "Cr\u00e9er",
    CREATE_BASELINE: "Cr\u00e9er une baseline",
    CREATE_BASELINE_LATEST: "Cr\u00e9er la baseline avec les derniers articles",
    CREATE_BASELINE_RELEASED: "Cr\u00e9er la baseline avec les derniers articles finalisés",
    CREATE_NEW_VERSION: "Cr\u00e9er une nouvelle version",
    DELETE: "Supprimer",
    DELETE_SELECTION: "Supprimer la s\u00e9lection",
    DELETE_SELECTION_QUESTION: "Supprimer la s\u00e9lection ?",
    DESCRIPTION: "Description",
    FILES: "Fichiers",
    FIRST_PAGE: "Première page",
    GO_TO_PAGE: "Aller à la page ...",
    ID_GENERATION: "G\u00e9n\u00e9ration de l'id",
    ITERATION: "Iteration",
    ITERATION_NOTE: "Note d'it\u00e9ration",
    ITERATION_NOTE_PROMPT_LABEL: "La note d'it\u00e9ration n'a pas \u00e9t\u00e9 d\u00e9finie. Souhaitez-vous l'ajouter ?",
    ITERATION_NOTE_PROMPT_CANCEL: "Ignorer",
    ITERATION_NOTE_PROMPT_OK: "Ajouter la note d'it\u00e9ration",
    LAST_PAGE: "Dernière page",
    MASK: "Masque",
    NEW_PART: "Nouvel article",
    NEW_PART_TEMPLATE: "Nouveau modèle d'article",
    NEW_PRODUCT: "Nouveau produit",
    NEW_VERSION: "Nouvelle version",
    NEW_VERSION_OF: "Nouvelle version de",
    NEXT_PAGE: "Page suivante",
    OBJECTS: "Objets",
    PART_NUMBER_HELP: "Num\u00e9ro de l'article",
    PART_TEMPLATE: "Modèle d'article",
    PART_TEMPLATES: "Modèles",
    PARTS: "Articles",
    PREVIOUS_PAGE: "Page pr\u00e9c\u00e9dente",
    PRODUCT_ID: "R\u00e9f\u00e9rence",
    PRODUCT_STRUCTURE: "Structure du produit",
    PRODUCTS: "Produits",
    PUBLISH: "Publier",
    QUICK_SEARCH: "Recherche rapide",
    RELEASE_SELECTION_QUESTION: "Finaliser la s\u00e9lection ?",
    ROOT_PART: "Article de tête",
    SEARCH: "Rechercher",
    STANDARD_PART_ALL: "Tous",
    STANDARD_PART_FALSE: "Non",
    STANDARD_PART_TRUE: "Oui",
    TITLE: "Titre",
    TYPE: "Type",
    PART_TYPE_HELP: "Type de l'article",
    DOCUMENT_TYPE_HELP: "Type du document",
    UNDO_CHECKOUT: "Annuler la r\u00e9servation",
    UNDO_CHECKOUT_QUESTION: "Annuler la r\u00e9servation ?",
    VERSION: "Version",
    VERSION_HELP: "Version de l'article",
    WORKFLOW: "Workflow",
    WORKSPACE: "Espace de travail",
    LAYERS: "Calques",
    NEW_LAYER: "Nouveau calque",
    NO_LAYERS: "Aucun calque",
    PART_NUMBER: "Numéro",
    PART_NAME: "Nom",
    AUTHOR: "Auteur",
    AMOUNT: "Quantité",
    CREATION_DATE: "Date de création",
    CHECKOUT_DATE: "Date de réservation",
    CHECKOUT_BY: "Réservé par",
    _DATE_FORMAT: "dd-mm-yyyy HH:MM:ss",
    CANCEL_CHECKOUT: "Annuler la réservation",
    CHECKIN: "Libérer",
    CHECKOUT: "Réserver",
    DELETE_MARKER: "Supprimer le marqueur",
    NEW_MARKER: "Créer un marqueur",
    NAME: "Nom",
    EMBED_SCENE: "Exporter la scène",
    CONTROLS_SHORTCUTS: "Raccourcis clavier/souris",
    KEYBOARD_SHORTCUTS: "Raccourcis clavier",
    MOUSE_CONTROLS: "Contrôles de la souris",
    MOVE_FORWARD: "Avancer",
    MOVE_BACKWARD: "Reculer",
    MOVE_LEFT: "Déplacer à droite",
    MOVE_RIGHT: "Déplacer à gauche",
    MOVE_UP: "Monter",
    MOVE_DOWN: "Descendre",
    LEAVE_NAV: "Quitter la navigation",
    MOVE: "Déplacer",
    MOVE_SCENE: "Se déplacer dans la scène",
    LEFT_CLICK: "clic gauche",
    RIGHT_CLICK: "clic droit",
    DBL_CLICK: "double clic",
    ENTER_NAV: "Commencer la navigation",
    MARKER_INFO: "Afficher des informations sur la note",
    SPACE: "espace",
    ROTATE_SCENE: "Pivoter la scène",
    SCROLL_UP: "défilement haut",
    SCROLL_DOWN: "défilement bas",
    GENERAL: "Général",
    ATTRIBUTES: "Attributs",
    CAD_FILE: "Fichier CAD",
    APPEND: "Ajouter",
    STANDARD_PART: "Article standard",
    SUB_PARTS: "Assemblage",
    CREATE_NEW_PART: "Créer un nouvel article",
    OR_ADD_PART: "Ou ajouter un article existant",
    NO_WEBGL: "Le navigateur ne supporte pas WebGL ou n'est pas activé.",
    TRUE: "Oui",
    FALSE: "Non",
    LINKS: "Liens",
    EXPORT: "Exporter",
    FULL_SCREEN: "Plein écran",
    CONFIG_SPEC: "Config spec",
    LATEST: "Dernière",
    SEARCH_PARTS: "Recherche d'articles",
    SEARCH_OPTIONS: "Options de recherche",
    PART_NAME_HELP: "partName",
    SEARCH_PART_CALLED: "Rechercher l'article",
    SEARCH_PART_BEGINNING: "Article commencant par",
    SEARCH_PART_ENDING: "Article finissant par",
    FLYING_MODE: "Mode libre",
    TRACKBALL_MODE: "Mode trackball",
    ORBIT_MODE: "Mode orbit",
    FIT_VIEW: "Centrer les objets visibles",
    MARKERS_SIZE_MIN: "Diminuer la taille des marqueurs",
    MARKERS_OPACITY: "Changer l'opacité des marqueurs",
    MARKERS_SIZE_MAX: "Augmenter la taille des marqueurs",
    VIEW_MODE: "Mode de vue",
    MARKERS: "Marqueurs",
    COMPONENT_SELECTED: "Article sélectionné",
    INSTANCE_SELECTED: "Instance sélectionnée",
    FLY_TO: "Atteindre",
    LOOK_AT: "Regarder",
    CLIPPING: "Couper",
    TOGGLE_ALL_LAYERS: "Basculer la visibilité des calques",
    APPEND_LAYER: "Créer un nouveau calque",
    SCENE_VIEW: "Scène",
    BOM_VIEW: "Liste des matériaux",
    OPTIONS: "Options",
    TAKE_SCREENSHOT: "Capture d'écran",
    GRID_SWITCH: "Afficher/Masquer la grille",
    LIFECYCLE_STATE: "Etat du cycle de vie",
    REFERENCE: "Référence",
    REVISION_NOTE: "Note de révision",
    MODIFICATION_DATE: "Date de modification",
    CUTPLAN: "Plan de coupe",
    EXPLODE: "Eclater",
    IN_PROGRESS: "En cours",
    RELEASE: "Finaliser",
    RELEASED: "Finalis\u00e9",
    MEASURE: "Mesure",
    NAVIGATION: "Navigation",
    TRANSFORM_CONTROLS: "Transformation",
    ROTATE: "Rotation",
    SCALE: "Echelle",
    REPLACE: "Réinitialiser",
    RESET_CAMERA: "Repositionner la caméra",
    SHOW_EDITED_MESHES: "Surligner les objets modifiés",
    COLLABORATIVE_LEAD: "Présentateur",
    PENDING: "Participant absent",
    PARTICIPANT: "Participant",
    CREATE_ROOM: "Démarrer une revue de maquette",
    INVITE: "Inviter des collaborateurs",
    EXIT: "Quitter la revue de maquette",
    WITHDRAW_INVITATION: "Retirer l'invitation",
    GIVE_HAND: "Donner la main",
    COLLABORATIVE_NO_MASTER: "absent",
    COLLABORATIVE: "Co-browsing",
    NO_PARTICIPANT: "Aucun participant. Invitez des utilisateurs depuis le menu Collaborateurs.",
    USERS_CONNECTED: "utilisateurs connectés",
    ROLES: "Rôles",
    NEW_ROLE: "Nouveau rôle",
    MANAGE_ROLES: "Gestion des rôles",
    ROLE_NAME: "Nom du rôle",
    ADD: "Ajouter",
    ALERT_ROLE_IN_USE: "Ce rôle ne peut être supprimé car il est utilisé dans un workflow",
    SHORTCUTS_TITLE: "Raccourcis clavier / souris",
    BLOCKER_TITLE: "Cliquez pour lancer la visualisation",
    BLOCKER_TEXT: "(Z, Q, S, D = Déplacer, ESPACE = Haut, CTRL = Bas, SOURIS = Regarder autour, ECHAP = Quitter)",
    ACL: "Droits",
    SAVE: "Enregistrer",
    CANCEL: "Annuler",
    USERS: "Utilisateurs",
    GROUPS: "Groupes",
    FORBIDDEN: "Interdit",
    READ_ONLY: "Lecture seule",
    FULL_ACCESS: "Accès complet",
    USE_ACL: "Utiliser les droits ?",
    SHARE: "Partager",
    CLOSE: "Fermer",
    SHARED_DOCUMENTS_TITLE: "Publier le document",
    SHARED_PARTS_TITLE: "Publier l'article",
    PUBLIC_ACCESS_TITLE: "Accès public au permalien",
    PRIVATE_SHARE_TITLE: "Accès privé",
    GENERATED_URL: "Lien généré",
    PASSWORD: "Mot de passe",
    CONFIRM: "Confirmer le mot de passe",
    PASSWORD_NOT_CONFIRMED: "Les champs mot de passe et confirmation doivent être identiques",
    EXPIRE_DATE: "Date d'expiration",
    FORM_HELPER: "Laissez ces champs vide si vous ne voulez pas spécifier de mot de passe ou de date d'expiration",
    PUBLIC_SHARE: "Partage public",
    PERMALINK: "Permalien",
    ACCEPT_VIDEO_INVITE: "Accepter",
    REJECT_VIDEO_INVITE: "Rejeter",
    VIDEO_INVITE_NOTIFICATION_TITLE: "Invitation Vidéo",
    VIDEO_INVITE_TEXT: "vous invite à démarrer une session vidéo.",
    UNREACHABLE: "Impossible d'envoyer l'invitation, l'utilisateur distant est hors-ligne",
    ERROR: "Erreur",
    REMOTE_HANGUP: "L'utilisateur distant a raccroché",
    CLOSING_PEER_CON: "Fermeture de la connexion ...",
    CALL_TO_TITLE: "Appel en cours",
    WAITING_USER_MEDIA: "En attente de l'entrée vidéo ... Veuillez accepter la demande de votre navigateur.",
    REMOTE_TIMEOUT: "L'utilisateur distant n'a pas répondu à temps. Appel terminé ...",
    REMOTE_BUSY: "L'utilisateur distant est occupé. Appel terminé ...",
    REMOTE_ACCEPT: "L'utilisateur distant a accepté l'appel. En attente de connexion ...",
    REMOTE_REJECT: "L'utilisateur distant a rejeté l'appel. Appel terminé ...",
    REMOTE_OFFLINE: "L'utilisateur distant est hors-ligne. Appel terminé ...",
    USER_MEDIA_FAILED: "Imposible d'accéder à votre entrée vidéo. Votre navigateur supporte-il le WebRTC ?",
    VIDEO_INVITATION_SENT: "L'invitation a été envoyée à l'utilisateur distant, en attente de l'acceptation ...",
    CONNECTING: "Connexion ...",
    CANNOT_CREATE_PC: "Impossible de créer la connexion, votre navigateur ne supporte pas le WebRTC.",
    SESSION_CONNECTING: "Connexion de la session ...",
    SESSION_OPENED: "Session connectée",
    REMOTE_STEAM_ADDED: "Flux vidéo de l'utilisateur distant ajouté",
    REMOTE_STEAM_REMOVED: "Flux vidéo de l'utilisateur distant enlevé",
    WAITING_REMOTE_VIDEO: "En attente de la vidéo de l'utilisateur distant.",
    CONNECTED: "Connecté",
    DEVICE_ERROR: "Imposible de se connecter à votre matériel audio/vidéo. Veillez à activer le WebRTC pour votre navigateur, et de vérifier les exceptions.",
    CHANNEL_NOT_READY_ERROR: "Impossible de se connecter au serveur d'appel, vérifiez que votre navigateur supporte les websocket, ou que votre FAI ne les bloque pas",
    DUPLICATE: 'Dupliquer',
    ADD_ISSUE: "Ajouter une anomalie",
    ADD_REQUEST: "Ajouter une requête",
    AFFECTED_ELEMENT: "El\u00e9ments affect\u00e9s",
    CHANGE_ITEM_ASSIGNEE: "Utilisateur assign\u00e9",
    CHANGE_ITEM_CATEGORY: "Cat\u00e9gorie",
    CHANGE_ITEM_PRIORITY: "Priorit\u00e9",
    CHECKOUTS: "R\u00e9serv\u00e9s",
    DUE_DATE: "Date d'\u00e9ch\u00e9ance",
    EDIT_ISSUE: "Editer l'anomalie",
    EDIT_MILESTONE: "Editer le jalon",
    EDIT_ORDER: "Editer l'ordre de modification",
    EDIT_REQUEST: "Editer la demande de modification",
    INITIATOR: "Initiateur",
    ISSUES: "Anomalies",
    MILESTONE: "Jalon",
    MILESTONES: "Jalons",
    NEW_ISSUE: "Nouveau rapport d'anomalie",
    NEW_MILESTONE: "Nouveau jalon",
    NEW_ORDER: "Nouvel ordre de modification",
    NEW_REQUEST: "Nouvelle demande de modification",
    ORDERS: "Ordres",
    ORDERS_NUMBER: "Ordres associ\u00e9s",
    REQUESTS: "Demandes",
    REQUESTS_NUMBER: "Demandes associ\u00e9es",
    LATEST_SHORT:"Dernières versions",
    RELEASED_SHORT:"Derni\u00e8re versions finalis\u00e9s",
    OPEN_NEW_WINDOW:"Ouvrir dans une nouvelle fenêtre"
});