define({
    CONFIGURATION:"Configuration",
    CONFIGURATION_ERROR:"Erreur de configuration",
    HOST:"Hôte",
    PORT:"Port",
    USER:"Utilisateur",
    PASSWORD:"Mot de passe",
    WORKSPACE:"Espace",
    WORKING_DIR:"Répertoire de travail",
    OK:"OK",
    CANCEL:"Annuler",
    THIS_COMPUTER:"ORDINATEUR",
    MY_FILES:" Mes fichiers",
    VERSIONED_FILES:"Fichiers versionnés",
    UNVERSIONED_FILES:"Fichiers non versionnés",
    NEW_PATH:"Nouveau dossier",
    REMOVE_PATH:"Supprimer des répertoires",
    CHOOSE_PATH:"Choisir un dossier",
    SELECT_PATH:"Choisir un dossier",
    PATH:"Dossier",
    OPTIONS:"Options",
    LOCAL_PATHS:"Dossiers locaux",
    FORCE:"Ecraser fichiers existants",
    RECURSIVE:"Récursif",
    BASELINE:"Baseline"
});